server:
  port: 5014
spring:
  application:
    name: authorization
#  cloud:
#    config:
#      uri: http://localhost:8888
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/role_permissions
    password: 'postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update # for production
    show-sql: 'true'
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#---
#spring:
#  application:
#    active:
#      profiles: test
#  cloud:
#    config:
#      uri: http://localhost:8888
#  datasource:
#    username: 'postgres'
#    url: jdbc:postgresql://localhost:5432/role_permissions_test
#    password: 'postgres'
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: 'true'
#    hibernate:
#      ddl-auto: create-drop
#      #ddl-auto: update # for production
#    show-sql: 'true'
