version: '3.8'
services:
  pg:
    image: postgres
    container_name: db_pg
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    restart: unless-stopped
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-db@db.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE:-False}
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
  postgres_data:
  pgadmin_data:
